1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [5]:
import numpy as np
matrix1 = np.random.randint(0,10,(3,3))
matrix2 = np.random.randint(0,10,(3,3))

print(matrix1)
print(matrix2)

dot = np.dot(matrix1,matrix2)
print(dot)



[[1 2 2]
 [7 6 4]
 [1 5 3]]
[[8 5 3]
 [5 9 4]
 [7 9 6]]
[[ 32  41  23]
 [114 125  69]
 [ 54  77  41]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [14]:
import numpy as np
matrix = [[55,25,15],[30,44,2],[11,45,77]]
print(matrix)
det = np.linalg.det(matrix)
print(det)

[[55, 25, 15], [30, 44, 2], [11, 45, 77]]
137180.0000000001
