1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [2]:
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)

sum = np.sum(mat)
print("\n Sum is :\n",sum)


 The Matrix is:
 [[5 6 4]
 [1 4 6]
 [4 0 6]]

 Sum is :
 36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [4]:
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)

col = np.sum(mat,axis =0)
print("\n Sum of Columns:\n",col)

row = np.sum(mat,axis =1)
print("\n Sum of Columns:\n",row)



 The Matrix is:
 [[5 3 5]
 [1 2 3]
 [3 5 2]]

 Sum of Columns:
 [ 9 10 10]

 Sum of Columns:
 [13  6 10]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [8]:
import numpy as np
mat = np.random.randint(0,15,(4,4))
print("\n The Matrix is:\n",mat)

min = np.min(mat)
print("\n Minimum Value is\n",min)

max = np.max(mat)
print("\n Maximum Value is\n",max)

mean = np.mean(mat)
print("\n Minimum Value is\n",mean)


 The Matrix is:
 [[ 1  8  9  8]
 [10  2 13  3]
 [14  0 13  1]
 [ 4 14 14 10]]

 Minimum Value is
 0

 Maximum Value is
 14

 Minimum Value is
 7.75


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [21]:
import numpy as np
mat = np.random.randint(0,99,(10,10))
print("\n The Matrix is:\n",mat)

print("\nThe 7th row is :\n",mat[7,:])

print("\nThe 4-8th row is :\n",mat[4:8,:])

print("\nThe value at (5,5) is :\n",mat[5,5])

print("\nThe 5th column) is :\n",mat[:,5])

print("\nThe 2-5th column) is :\n",mat[:,2:5])




 The Matrix is:
 [[29 16 85  7 51 83 29 41 12 91]
 [17 77 27 10 14 53 69  6  1 46]
 [85 10 58 82 10 97 69 52 69 36]
 [ 2 63 56 68 71 48 17 17 32 19]
 [ 5 27  2  1 19 18 92 44 72 81]
 [42 33 60 61  9 33 92 65 93 65]
 [34 45 88 51  8 58  0 94 73 87]
 [ 0  5 63 10 63 30 20 54 40 97]
 [96 44 13 40 37 21 73  9 23  2]
 [ 5 11 12 62 23 90 39 72  5 25]]

The 7th row is :
 [ 0  5 63 10 63 30 20 54 40 97]

The 4-8th row is :
 [[ 5 27  2  1 19 18 92 44 72 81]
 [42 33 60 61  9 33 92 65 93 65]
 [34 45 88 51  8 58  0 94 73 87]
 [ 0  5 63 10 63 30 20 54 40 97]]

The value at (5,5) is :
 33

The 5th column) is :
 [83 53 97 48 18 33 58 30 21 90]

The 2-5th column) is :
 [[85  7 51]
 [27 10 14]
 [58 82 10]
 [56 68 71]
 [ 2  1 19]
 [60 61  9]
 [88 51  8]
 [63 10 63]
 [13 40 37]
 [12 62 23]]
