1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [2]:
import numpy as np

mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)

print("Trace of the Array is: \n",mat.trace())


Array
 [[13  8 14  9]
 [10 11 10  4]
 [ 7  7 12 13]
 [ 4  0  4 13]]
Trace of the Array is: 
 49


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [7]:
import numpy as np
mat = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Matix\n",mat)
print("\nThe Inverse of Matrix is :\n",np.linalg.inv(mat))


Matix
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The Inverse of Matrix is :
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [9]:
import numpy as np

mat = np.random.randint(0,8,(3,3))
print("Array\n",mat)
print("\nThe Norm of the Matrix is\n",np.linalg.norm(mat))


Array
 [[4 5 4]
 [2 0 1]
 [4 5 7]]

The Norm of the Matrix is
 12.328828005937952


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [14]:
import numpy as np

mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)
print("\nThe EigenValue and EigenVectors of the Matrix is\n",np.linalg.eig(mat))

Array
 [[14  1  3  4]
 [10  6 14  9]
 [10  5  1  2]
 [10 12 13  7]]

The EigenValue and EigenVectors of the Matrix is
 (array([27.59438487,  7.18513766, -6.03009815, -0.74942438]), array([[-0.30606248, -0.4572804 ,  0.08462868, -0.13564676],
       [-0.6061312 ,  0.50005988,  0.76433858,  0.10685687],
       [-0.28007664, -0.09946251, -0.621734  , -0.500128  ],
       [-0.67859252,  0.72865765, -0.14856433,  0.84855969]]))
