1. Generate a 3 x 3 matrix using random module.

In [ ]:
import numpy as np
  
matrix = np.random.randint(10, size=(3, 3))
print(matrix)


[[3 8 8]
 [3 7 3]
 [1 5 3]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [ ]:
import numpy as np

matrix = np.random.randint(10,size=(4,4))
print(matrix)

newm = matrix.reshape(2,8)
print("The Reshaped Matrix is \n",newm)
vstack = np.vstack(newm,)
print("Vertically Stacked Matrix is \n",vstack)
hstack = np.hstack(newm)
print("Horizontally Stacked Matrix is \n",hstack)

[[2 2 2 2]
 [0 9 9 0]
 [4 5 5 3]
 [0 2 1 5]]
The Reshaped Matrix is 
 [[2 2 2 2 0 9 9 0]
 [4 5 5 3 0 2 1 5]]
Vertically Stacked Matrix is 
 [[2 2 2 2 0 9 9 0]
 [4 5 5 3 0 2 1 5]]
Horizontally Stacked Matrix is 
 [2 2 2 2 0 9 9 0 4 5 5 3 0 2 1 5]
