N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [7]:
import numpy as np

mat1 = np.random.randint(0,8,(3,3))
mat2 = np.random.randint(10,19,(3,3))

print("Matrix A\n" ,mat1)

print("\nMatrix B\n" ,mat2)

out = np.multiply.outer(mat1,mat2)
print("Outer Products\n",out)

dot = np.dot(mat1,mat2)
print("Dot Products\n",dot)

Ele = np.multiply(mat1,mat2)
print("Element Wise\n",Ele)


Matrix A
 [[2 4 4]
 [0 3 1]
 [0 5 3]]

Matrix B
 [[10 12 18]
 [17 15 16]
 [17 12 14]]
Outer Products
 [[[[20 24 36]
   [34 30 32]
   [34 24 28]]

  [[40 48 72]
   [68 60 64]
   [68 48 56]]

  [[40 48 72]
   [68 60 64]
   [68 48 56]]]


 [[[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[30 36 54]
   [51 45 48]
   [51 36 42]]

  [[10 12 18]
   [17 15 16]
   [17 12 14]]]


 [[[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[50 60 90]
   [85 75 80]
   [85 60 70]]

  [[30 36 54]
   [51 45 48]
   [51 36 42]]]]
Dot Products
 [[156 132 156]
 [ 68  57  62]
 [136 111 122]]
Element Wise
 [[20 48 72]
 [ 0 45 16]
 [ 0 60 42]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [14]:
import numpy as np

mat = np.random.randint(0,16,(4,4))
print("Matrix is \n", mat)

#adding 4(scalar) to the matrix
scal = 2
addScal = mat + scal
print("\n Scalar Matrix\n",addScal)

#matrix broadcasting
nums = np.array([1,2,3,4])
mult = mat * nums
print("\nThe Multiplication by broadcasting\n",mult)



Matrix is 
 [[13 13 14  1]
 [15 10 11 11]
 [15  7 15  7]
 [ 6 11  9  8]]

 Scalar Matrix
 [[15 15 16  3]
 [17 12 13 13]
 [17  9 17  9]
 [ 8 13 11 10]]

The Multiplication by broadcasting
 [[13 26 42  4]
 [15 20 33 44]
 [15 14 45 28]
 [ 6 22 27 32]]
